# Generated by Django 6.1.1 on 2026-09-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="is_bonus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payout",
            name="percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="destination_address",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
