# Generated by Django 6.1.1 on 2026-09-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_payoutwindow_payout_payout_window"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptoaccount",
            name="is_platform",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="banned_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
