# Generated by Django 6.1.1 on 2026-09-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_user_email_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="provider_order_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="provider_token",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
    ]
