# Generated by Django 6.1.1 on 2026-09-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_kycsubmission_first_name_kycsubmission_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="provider_id",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="provider_id",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
