# Generated by Django 5.0.3 on 2026-09-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_cryptomus_provider_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(fields=["status"], name="api_investm_status_a80ff4_idx"),
        ),
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(
                fields=["user", "status"], name="api_investm_user_id_6c2a73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="api_notific_user_id_16328d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(fields=["status"], name="api_payment_status_4545e1_idx"),
        ),
        migrations.AddIndex(
            model_name="pricesnapshot",
            index=models.Index(
                fields=["coin", "captured_at"], name="api_pricesn_coin_id_6684c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawal",
            index=models.Index(fields=["status"], name="api_withdra_status_d3e117_idx"),
        ),
        migrations.AddIndex(
            model_name="withdrawal",
            index=models.Index(
                fields=["user", "status"], name="api_withdra_user_id_8b639f_idx"
            ),
        ),
    ]
