# Generated by Django 5.0.3 on 2026-09-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_withdrawal_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="chain",
            field=models.CharField(
                choices=[
                    ("TRC20", "TRC20"),
                    ("ERC20", "ERC20"),
                    ("BEP20", "BEP20"),
                    ("BEP2", "BEP2"),
                    ("TON", "TON"),
                ],
                default="TRC20",
                max_length=30,
            ),
        ),
    ]
